# Functions and structs
where_single_line = true
struct_field_align_threshold = 20

# Match blocks
force_multiline_blocks = true
match_block_trailing_comma = true

# Imports
reorder_imports = true
reorder_imported_names = true
reorder_imports_in_group = true
reorder_extern_crates = true
reorder_extern_crates_in_group = true

# Other
error_on_line_overflow = false
condense_wildcard_suffixes = true
format_strings = true
use_try_shorthand = true
