language: rust
rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx
  - windows

matrix:
  allow_failures:
    - rust: nightly
    - os: windows
  fast_finish: true

cache: cargo

stages:
  - test
  - bin
  - doc

jobs:
  include:
    - stage: test
      script:
        - cargo build --verbose
        - cargo test --verbose -- --nocapture
    - stage: bin
      script:
        - cargo build --verbose --example ftml
    - stage: doc
      script:
        - cargo doc --verbose

notifications:
  email:
    on_success: change
    on_failure: always
