[package]
name = "wikidot-to-html"
version = "0.0.6"
authors = ["Ammon Smith <ammon.i.smith@gmail.com>"]
edition = "2018" # this refers to the Cargo.toml version

[lib]
name = "wikidot_html"
path = "src/lib.rs"

[[bin]]
name = "wikidot2html"
path = "src/main.rs"

[dependencies]
clap = "2" # bin-only
either = "1.5"
horrorshow = "0.6"
lazy_format = "1.3"
lazy_static = "1"
log = "0.4"
pest = "2.1"
pest_derive = "2.1"
regex = "1"
