[package]
name = "wikidot-to-html"
version = "0.0.1"
authors = ["Ammon Smith <ammon.i.smith@gmail.com>"]
edition = "2018" # this refers to the Cargo.toml version

[lib]
name = "wikidot_html"
path = "src/lib.rs"

[[bin]]
name = "wikidot2html"
path = "src/main.rs"

[dependencies]
clap = "2" # bin-only
lalrpop-util = "0.16.3"
lazy_static = "1"
regex = "1"

[build-dependencies]
lalrpop = "0.16.3"
